- fix in checking is netforking is up.
Changed files:
    sendmail.init -> 1.5

diff --git a/sendmail.init b/sendmail.init
--- a/sendmail.init
+++ b/sendmail.init
@@ -19,7 +19,10 @@
 [ -f /etc/sysconfig/sendmail ] && . /etc/sysconfig/sendmail
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Sendmail service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
